

ENUM_LOG_HEAD(LogLevel) 
ENUM_LOG_ITEM(ALL     , 0)
ENUM_LOG_ITEM(DEBUGE  , 1)
ENUM_LOG_ITEM(INFO    , 2)
ENUM_LOG_ITEM(WARNING , 3)
ENUM_LOG_ITEM(ERROR   , 4)
ENUM_LOG_ITEM(FATAL   , 5)
ENUM_LOG_ITEM(OFF     , 6) 
ENUM_LOG_TAIL(LogLevel) 




